name: Build-Dylib
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"

      - name: Build dylib
        run: |
          export THEOS=~/theos
          make

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Vncheat-Result
          path: .theos/obj/*.dylib
