name: Build-Dylib
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Theos & SDK
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip master.zip
          mv sdks-master/* ~/theos/sdks
          brew install ldid
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Build Dylib
        run: |
          export THEOS=~/theos
          make FINALPACKAGE=1

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Vncheat-Result
          path: .theos/obj/Vncheat.dylib

